spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/projeto
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.file.name=logs/app.log
logging.level.root=warn
logging.level.com.example.demo.controller=trace
logging.level.org.springframework.security=trace

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=xdogchupetinha123@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

secret="secret"
jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

spring.security.oauth2.client.registration.google.client-id=486509186348-gkpu0e3dq847v5g3pa1vi4co18i387vp.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

#spring.main.allow-bean-definition-overriding=true

